### ISSUE TITLE
Add option to store AGS username/password encrypted.

### ISSUE THREAD

**Issue by sitlaBarry** [agrc/forklift#168]
Our sys admin doesn't like the idea of storing usernames and passwords in environment variables (FORKLIFT_AGS_USERNAME, FORKLIFT_AGS_PASSWORD.) It would be nice to have the option of storing these as hashes.

**Comment by steveoh** [comment]
### brainstorming

Here's what we think is best:

Hashing is one way, so we could use that to set the hash but we could never get the values. so :-1:

Asymmetric encryption is the best solution, but since its only as secure as the private key that would most likely reside on the same machine as forklift, it doesn't offer much over the next much simpler and similar solution.

Base64 encode the values. It's two way and simple and hides the values from plain sight which seems to be the concern that you have. 

### implementation

1. Add a cli option to set the username/password encoded so that it doesn't need to be a separate step.
1. decode the values before using it. 
1. celebrate

**Comment by stdavis** [comment]
Might I suggest that the lift command checks for the env vars and automatically prompts the user for them if they don't exist.

**Comment by steveoh** [comment]
that seems ok in a non automated use case but when it's a scheduled task that would hang the process.

**Comment by sitlaBarry** [comment]
This is no longer needed as it is overkill. 

I was over the line during a league game. My apologies.
