### ISSUE TITLE
Help Command

### ISSUE THREAD

**Issue by stdavis** [agrc/forklift#222]
From Josh Groeneveld (GitHub username?):
>I just upgraded to forklift 8.4.1 this morning.  I've had trouble with forklift where running the command: forklift -h doesn't do anything, but "forklift help" does.  Is it supposed to work this way?  Per the docs on the Github page, I thought "forklift -h" was supposed to show the list of available commands.
>![image](https://user-images.githubusercontent.com/1326248/35001255-a981fb06-faa3-11e7-892a-6a8872ffea48.png)
>Not a huge issue...all of the other forklift commands that I've used work.  Let me know if you have any suggestions.
>Thanks!

Sounds like an issue with docopt?

**Comment by joshgroeneveld** [comment]
@stdavis While I just upgraded to version 8.4.1 this morning, I've noticed this issue with previous versions...I just hadn't documented them.

**Comment by steveoh** [comment]
forklift hasn't had the [-h or --help](https://github.com/agrc/forklift/blob/master/src/forklift/__main__.py#L4-L18) flag before. I don't think the docopt dependency has moved since the project started.

if you type `forklift` you will get the basic help screen. 

The error you are getting is on the [tractor emoji](https://github.com/agrc/forklift/blob/master/src/forklift/__main__.py#L4). We will probably have to remove that to make the extended help screen work.

**Comment by joshgroeneveld** [comment]
So if forklift hasn't had the -h or --help flag, why is it listed on the main page for the repo?
![forklift_homepage](https://user-images.githubusercontent.com/4296780/35013829-d4e280ea-facb-11e7-8aae-8d9cd527be53.PNG)

**Comment by steveoh** [comment]
@joshgroeneveld go to [releases](https://github.com/agrc/forklift/releases) and download version 8.4.2. It will have the help command fix as well as some other fixes.

If you want to work from master, you can download the code but when you install with pip you will have to use `pip install ./ -U` to force an update. This is required if the version number has not changed since your last installation. 

Cheers!
