### ISSUE TITLE
define plugin baseclass and structure

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#3]
I gave [this a shot](https://github.com/agrc/Parcels/blob/master/scripts/Update.py) in the parcels application. Let's put some [incantation of this](https://github.com/agrc/Parcels/blob/master/scripts/Update.py#L14-L31) into forklift.

Do we want to have to checkout forklift into every project so the update script can be imported and inherited from? Do we checkout one version into each server where we have update scripts?

**Comment by stdavis** [comment]
I think that I like the idea of pip installing it into every project so that we have something to work with. Then we would also check it out at a parent level on each update server. In this case we may want to look at how to handle versioning of it at the update server level. Could we build the master script with the ability to run different versions of plugins? Seems possible.

I think that I need a walkthrough of this but it looks like it's headed in the right direction to me.

**Comment by stdavis** [comment]
I was just thinking that we should try and create a happy path for running legacy update scripts without having to modify them heavily. Then that would allow us to quickly bring forklift online and incrementally upgrade each project over time.

**Comment by steveoh** [comment]
do you have any ideas on ways to accomplish that?

**Comment by stdavis** [comment]
What about using [subprocess](https://docs.python.org/2/library/subprocess.html) to run the legacy scripts? Just haven't control to run them in sequence would be a major upgrade.
